name = "bulk-terabox-dl"
compatibility_date = "2024-05-18"

// wrangler.toml
[build]
command = "npm run build"

[build.upload]
dir = "dist"
main = "index.js"
format = "modules"

[site]
bucket = "./src/page"  # Ensure this path is correct and points to your build output directory

[vars]
JS_TOKEN = "3D7E5F7E8F8A71A839D6BDE718891A909063E0A4C8C054C0E8D89DC20C0A74FAAAA247DB0AB3A424A027A7B33FF54F6AA67327125C68D46D7E299ADCB80F7129"
DP_LOGID = "10989800961051610019"
COOKIES = "lang=en; __bid_n=18e557179cfaf038dc4207; _ga=GA1.1.702794740.1710830487; __stripe_mid=4f4a0c69-1e26-4051-9bb9-d6fbdc3aaac85e7d18; ndus=YvcVqeCteHuibdmxOvTVyAe0DXJJkE1QwJ5ldM_s; TSID=puA4Hfjuj4K4kdHRkTrwfsMJV8P6T5kt; browserid=xUeIE3PmrNUp3DkUatFGydwKe1mYkqTvDT1zuxYRMfgH2hnCVKJAJ7GIbA4=; csrfToken=GQk8vvDlstReYcYgqbNuVKtn; ab_ymg_result= ndut_fmt=94F7F28C5D098439160AD919EEC5633451A3C3D73055D3480BFF1004D071E38D; ab_sr=1.0.1_N2E5ZjdmYmIyMjZhYmM5MzUwZjU3ZDE5NmM2NmVhOWYyMTRkN2RhZjc3MGM1NjFhMzUxNDMzMzU2ZTkwNDdkNjlhNzVlNmJhYzE1Y2VmYzQ5ZGI4ODNkOTA3ZTlkNjA2N2YxZGM2NTc2NzA5ZDU2NDY2YjRiOTFjZWZlYWNlYzU4ZWUyN2EzMjA2ZDFlOWUwMTIzZTRlZDAwNWZiZjA5Zg==;"
